services:
  db:
    container_name: postgres
    image: "postgres:16-alpine"
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sales-order


  web:
    image: docker.io/library/sales-order:0.0.1-SNAPSHOT
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=order-sales


volumes:
  postgres_data: