version: '3.8'
services:
  db:
    container_name: postgres
    image: "postgres:16-alpine"
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sales-order
    networks:
      - app_network


  web:
    image: "docker.io/library/sales-order:0.0.1-SNAPSHOT"
    container_name: "sales-order-api"
    ports:
      - "8080:8080"
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=order-sales
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
